### ISSUE TITLE
为何会出现ｌｏｓｓ为ｎａｎ的情况

### ISSUE THREAD

**Issue by babyjia** [JindongJiang/WeightedLoss_Convolutional_Pose_Machines_PyTorch#2]
对ｃｏｄｅ的改动仅仅将ｂａｔｃｈｓｉｚｅ中的ｄｅｆａｕｌｔ＝３６改成了４　否则跑不起来，但是一开始ｌｏｓｓ就等于ｎａｎ了

./model/ckpt_epoch_0.00_batch_id_1.pth has been successfully saved
Step:    60 Train Epoch:   1 [ 240/11000 (2.2%)]    Loss: nan [28.90s every  120 data]
Traceback (most recent call last):
  File "cpm_train.py", line 203, in <module>
    train()
  File "cpm_train.py", line 126, in train
    writer.add_histogram(name, param.clone().cpu().data.numpy(), global_step)
  File "/mnt/lustre/zhangjiaqi/anaconda3/envs/python36/lib/python3.6/site-packages/tensorboardX/writer.py", line 328, in add_histogram
    self.file_writer.add_summary(histogram(tag, values, bins), global_step)
  File "/mnt/lustre/zhangjiaqi/anaconda3/envs/python36/lib/python3.6/site-packages/tensorboardX/summary.py", line 112, in histogram
    hist = make_histogram(values.astype(float), bins)
  File "/mnt/lustre/zhangjiaqi/anaconda3/envs/python36/lib/python3.6/site-packages/tensorboardX/summary.py", line 119, in make_histogram
    counts, limits = np.histogram(values, bins=bins)
  File "/mnt/lustre/zhangjiaqi/anaconda3/envs/python36/lib/python3.6/site-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.

**Comment by JindongJiang** [comment]
你好，请尝试减小initial learning rate

**Comment by babyjia** [comment]
好使～Ｏ（∩＿∩）Ｏ谢谢
