### ISSUE TITLE
训练内存问题

### ISSUE THREAD

**Issue by hanke580** [JindongJiang/WeightedLoss_Convolutional_Pose_Machines_PyTorch#5]
作者大大你好！
我在训练时出现了内存过大错误
需要分配46GB的RAM
请问为什么会到这这种情况呢错误代码如下

(pytorch) hanke@Garuda:~/WeightedLoss_Convolutional_Pose_Machines_PyTorch-master$ python -W ignore::UserWarning cpm_train.py --lsp-root /DATACENTER/5/cpm/data/LSP --ckpt-dir ./model  --summary-dir ./summary --cuda
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fc2ac38da90>>
Traceback (most recent call last):
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
    self._shutdown_workers()
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
    self.worker_result_queue.get()
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/queues.py", line 337, in get
    return _ForkingPickler.loads(res)
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 151, in rebuild_storage_fd
    fd = df.detach()
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 493, in Client
    answer_challenge(c, authkey)
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 732, in answer_challenge
    message = connection.recv_bytes(256)         # reject large message
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError: 
Traceback (most recent call last):
  File "cpm_train.py", line 203, in <module>
    train()
  File "cpm_train.py", line 112, in train
    pred_6 = model(image, center_map)
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hanke/WeightedLoss_Convolutional_Pose_Machines_PyTorch-master/cpm_model.py", line 199, in forward
    conv7_stage1_map = self._stage1(image)  # result of stage 1
  File "/home/hanke/WeightedLoss_Convolutional_Pose_Machines_PyTorch-master/cpm_model.py", line 82, in _stage1
    x = self.pool2_stage1(F.relu(self.conv2_stage1(x)))
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/hanke/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: $ Torch: not enough memory: you tried to allocate 46GB. Buy new RAM! at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/TH/THGeneral.cpp:204

**Comment by JindongJiang** [comment]
你好，请问你在用cpu还是gpu呢？
